<<<<<<< HEAD
baseURL = "https://erwinaris.github.io/"
=======
baseURL = "http://erwinaris.github.io/"
>>>>>>> b466d83469e5435c4ee513ac257ba287fe72fe38
languageCode = "en-us"
title = "Hi, There !"
description = "Welcome to my website for learn to programming"

theme = "semeru"

[params]
description = "Welcome to my website for learn to programming"
aboutTitle = "About Me"
about = """My name is Erwin Aris prayogo, i live in Lampung, Indonesia. More than 2 years experience in web developer and mobile developer include wordpress development,
            flutter development, hugo development, python, php, and dart.
            I use GNU/Linux to create and write the code computer program."""
<<<<<<< HEAD
keywords = "blog, erwin"
=======
keywords = ""
>>>>>>> b466d83469e5435c4ee513ac257ba287fe72fe38
images = ["/img/about-hero.jpg"]


############### css and javascript ##################

<<<<<<< HEAD

[[ params.plugins.css]]
URL = "plugins/css/materialize.min.css"

[[ params.plugins.css ]]
URL = "plugins/css/materialize.css"

[[ params.plugins.js ]]
URL = "plugins/js/materialize.js"
=======
[[ params.plugins.css ]]
URL = "plugins/css/materialize.css"
[[ params.plugins.css]]
URL = "plugins/css/materialize.min.css"
>>>>>>> b466d83469e5435c4ee513ac257ba287fe72fe38

[[ params.plugins.js ]]
URL = "plugins/js/materialize.min.js"

[[ params.plugins.js ]]
<<<<<<< HEAD
URL = "plugins/js/initialize.js"
=======
URL = "plugins/js/materialize.js"
>>>>>>> b466d83469e5435c4ee513ac257ba287fe72fe38


########### icons fontawesome ################

[[ params.icons ]]
icon = "fab fa-facebook-square"
link = "https://web.facebook.com/erwin.prayoga.359/"

[[ params.icons ]]
icon = "fab fa-instagram"
link = "https://www.instagram.com/erwin_aris_prayogo/"

[[ params.icons ]]
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/in/erwin-aris-prayogo-504119157/"

[[ params.icons ]]
icon = "fab fa-github-square"
link = "https://github.com/erwinaris"


################## menu #######################
[ menu ]
    [[ menu.main ]]
    name = "Dart"
    URL = "dart"

    [[ menu.main ]]
    name = "Portfolio"
    URL = "#"